Advanced web agent with sources
Mirascope/mirascope pull request #612
Opened 2024-10-09 14:26 UTC by Balogunolalere

Advanced tutorial for creating Advanced web agent with sources

2024-10-15 02:09 UTC, koxudaxi requested changes
@Balogunolalere
Thank you for creatin the awsome PR.
I left comments for just a few things.

2024-10-15 02:09 UTC, koxudaxi commented on docs/tutorials/more_advanced/web_search_agent_with_sources.ipynb
> +        "    reasoning: str = Field(description=\"The reasoning behind the query optimization\")"
Is `OptimizedQuery` not used?

2024-10-15 12:51 UTC, koxudaxi commented
Also, Could you please add your notebook in the `mkdcos.yml`? to show it on the menu. 
https://github.com/Mirascope/mirascope/blob/6a0346a89b327cdad7711d27bb329c3faf79fb2c/mkdocs.yml#L159-L177

2024-11-08 08:24 UTC, koxudaxi approved these changes

2024-11-08 19:06 UTC, willbakst approved these changes

2024-11-08 19:10 UTC, merged